apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: base.mongo.com
    external-dns.alpha.kubernetes.io/ttl: "30"
spec:
  hostname: base-1
  subdomain: default-subdomain
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend