apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: mongo.amordemaria.com
spec:
  type: ClusterIP
  # type: LoadBalancer
  ports:
  # - protocol: TCP
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  rules:
  - host: mongo.amordemaria.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mongo
            port:
              number: 27017