apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo
# this is where you you add your reserved ip
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mongo-ip 
  labels:
    app: mongo
spec:
  backend:
    serviceName: mongo
    servicePort: 27017