apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: mongo.amordemaria.com
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo
  annotations:
    kubernetes.io/ingress.class: mongo
    argocd.argoproj.io/sync-options: Validate=false
spec:
  rules:
  - host: mongo.amordemaria.com
    http:
      paths:
      - path: /testpath
        backend:
          service:
              name: mongo-svc
              port: 
                number: 27017
      
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mongo
#   annotations:
#     kubernetes.io/ingress.class: mongo
#   labels:
#     app: mongo
# spec:
#   rules:
#   - host: mongo.amordemaria.com
#     http:
#       paths:
#       - backend:
#           serviceName: mongo
#           servicePort: 27017
#         path: /

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mongo
#   annotations:
#     kubernetes.io/ingress.class: mongo
# spec:
#   rules:
#   - host: mongo.amordemaria.com
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#              name: mongo
#              port: 
#                number: 27017
#   - host: mongo.amordemaria.com
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#              name: mongo
#              port: 
#                number: 27017
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: mongo
# # this is where you you add your reserved ip
#   annotations:
#     kubernetes.io/ingress.global-static-ip-name: mongo-ip 
#   labels:
#     app: mongo
# spec:
#   backend:
#     serviceName: mongo
#     servicePort: 27017

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mongo
#   annotations:
#     kubernetes.io/ingress.class: mongo
#     argocd.argoproj.io/sync-options: Validate=false
# spec:
#   rules:
#   - host: mongo.example.com
#     http:
#       paths:
#       - backend:
#           serviceName: mongo
#           servicePort: 27017
#         path: /
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mongo
#   annotations:
#     kubernetes.io/ingress.class: mongo
# spec:
#   rules:
#   - host: mongo.example.com
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#              name: mongo
#              port: 
#                number: 27017
#   - host: mongo.example.com
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#              name: mongo
#              port: 
#                number: 27017
